### ISSUE TITLE
Use CalendarSelector for project add/edit start & end date

### ISSUE THREAD

**Issue by moncapitaine** [progwise/timebook#24]
![image](https://user-images.githubusercontent.com/16672443/128336942-00d84a56-fc80-4ae1-9ae0-0577f8b5d0e9.png)

**Comment by moncapitaine** [comment]
![image](https://user-images.githubusercontent.com/16672443/128336983-255f06fc-ad22-44a3-9126-14449e2ed33d.png)

**Comment by moncapitaine** [comment]
leave the input for both dates but add a calendar icon to the right

**Comment by moncapitaine** [comment]
only date

**Comment by moncapitaine** [comment]
start = startDate (no time)
end = endDate (no time)

bonus:

start < end

**Comment by moncapitaine** [comment]
Why you closed it???

**Comment by PascalHelbig** [comment]
This was already done a while ago.
