### ISSUE TITLE
Implement new date navigator in week view

### ISSUE THREAD

**Issue by moncapitaine** [progwise/timebook#368]
date must be in route

_/time/week?date=2022-06-10_

or

_/time?date=2022-06-10_

<img width="571" alt="image" src="https://user-images.githubusercontent.com/16672443/171855546-333893f6-446e-4e37-bc02-3d3357ae2538.png">
<img width="345" alt="image" src="https://user-images.githubusercontent.com/16672443/172115311-718fd2a7-21f4-4c7c-9a17-b53634e75e15.png">
<img width="405" alt="image" src="https://user-images.githubusercontent.com/16672443/172115767-fa4b6ea4-fab4-4814-b1ab-49d949bbb848.png">

see https://date-fns.org/docs/Getting-Started

**Comment by PascalHelbig** [comment]
fixed in #421
