### ISSUE TITLE
Bug when deploying with Dockerfile type DO app

### ISSUE THREAD

**Issue by moncapitaine** [progwise/timebook#550]

**Comment by moncapitaine** [comment]
https://cloud.digitalocean.com/apps/00b29984-4dc6-4ea4-be03-d30333868767/deployments/c4b6c09c-abad-45e7-bf67-d984c21dbdaa?i=b9dec7

**Comment by PascalHelbig** [comment]
I found the problem. There was a run command defined in the App settings in DigitalOcean, that does not exist in our pulumi config.
