### ISSUE TITLE
Bug when creating a new team

### ISSUE THREAD

**Issue by moncapitaine** [progwise/timebook#552]
The timebook uses the useCreateTeamMutation with the teamSlug in it and I cannot find the place where this is defined...

Why is he trying to use a teamSlug for the api url in this mutation?

![Image](https://user-images.githubusercontent.com/16672443/199279417-2f98c2c6-7356-4cab-b48e-de07d5e8a3f1.png)

![Image](https://user-images.githubusercontent.com/16672443/199279198-5b3fe68d-16d6-4df4-af42-f50fbba21478.png)

**Comment by PascalHelbig** [comment]
This issue occurs when the `.env` file inside the `/apps/web` folder is missing.

I created the follow-up ticket #557 to find a better way to handle .env files in our monorepo.
