### ISSUE TITLE
Create a Button component

### ISSUE THREAD

**Issue by PascalHelbig** [progwise/timebook#72]
For all our forms, we need a button to interact with.

Create a `Button` component that returns a HTML `button` tag with the following props:
- `type` (possible values: `button` (default) or `submit`)
- `disabled` (boolean, default to `false`)
- `variant` (possible values: `primary` or `secondary`) - use different background colors to indicate variant
- `children`

Place the file at `/app/frontend/components/button/button.tsx`.

Replace both buttons in `app/frontend/components/projectForm/projectForm.tsx` with the new component.

Ressources (that might help):
- https://beta.reactjs.org/learn/passing-props-to-a-component (How to use props)
- https://tailwindcss.com/ (How we style components in our project; ⚠️ In the examples they use the `class`-attribute, in React we have to use the `className` prop instead)

**Comment by moncapitaine** [comment]
![image](https://user-images.githubusercontent.com/16672443/142014632-b72f1d13-3067-4012-af1e-1fa3b6438b12.png)
