### ISSUE TITLE
shorter title for lock button

### ISSUE THREAD

**Issue by moncapitaine** [progwise/timebook#780]
![Image](https://user-images.githubusercontent.com/16672443/237414426-6e5e2996-72cb-4ff2-9004-6fe338f0ea5e.png)

Only 'lock' is enough

**Comment by jobayer12** [comment]
@moncapitaine 
I was trying to set up this project in my local environment. I set all the .env variables and run it locally. The database migration worked properly. But when I opened the project on  http://localhost:3000. It redirected me to the sign-in page. When I clicked on the "sign in with GitHub" / "sign in with email" nothing is happening. Does anyone help me to set up this project in the local environment properly?

![Image](https://github.com/progwise/timebook/assets/26854413/b24ec946-1155-4b96-b19f-41d2218e0b31)
