### ISSUE TITLE
Tracking Buttons in Week Table should be next to each other

### ISSUE THREAD

**Issue by PascalHelbig** [progwise/timebook#812]
![Image](https://user-images.githubusercontent.com/1886867/265014166-6870a9b4-b8ff-4baf-8c4a-64afee676d9a.png)

**Comment by yehoki** [comment]
Would this be enough? 
```
<div className="flex items-center gap-2">
        <Button variant="primary" onClick={() => stopTracking({})}>
          <BiPause />
        </Button>
        <Button variant="danger" onClick={() => setIsCancelModalOpen(true)}>
          <BiBlock />
        </Button>
</div>
```

Not sure if I'm allowed to contribute here, let me know I'll happily add a pull request to it

**Comment by PascalHelbig** [comment]
Hey @yehoki, nice to meet you. I think your solution is perfect.

> Not sure if I'm allowed to contribute here, let me know I'll happily add a pull request to it

Sure, we are happy about every pull request. 😄
